const state={password:sessionStorage.getItem('wclAdminPassword')||'',events:[],recruiters:[]};
const $=id=>document.getElementById(id);const authHeaders=()=>({'x-admin-password':state.password});
async function api(path,options={}){const headers={...authHeaders(),...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})};const r=await fetch(path,{...options,headers});const type=r.headers.get('content-type')||'';const d=type.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(d?.error||d||'Request failed.');return d}
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function showDashboard(){ $('loginCard').hidden=true;$('dashboard').hidden=false;$('logoutButton').hidden=false } function showLogin(){ $('loginCard').hidden=false;$('dashboard').hidden=true;$('logoutButton').hidden=true }
async function loadAll(){await Promise.all([loadRecruiters(),loadEvents(),loadBonzo()])}
async function loadRecruiters(){const d=await api('/.netlify/functions/recruiters');state.recruiters=d.recruiters||[];renderRecruiters();renderEventRecruiters()}
function renderEventRecruiters(){const active=state.recruiters.filter(r=>r.active);$('eventRecruiters').innerHTML=active.length?active.map(r=>`<label class="check"><input type="checkbox" name="recruiterIds" value="${esc(r.id)}"> ${esc(r.name)}</label>`).join(''):'<p>Add team members first.</p>'}
function renderRecruiters(){const list=$('recruitersList');if(!state.recruiters.length){list.innerHTML='<p>No team members yet.</p>';return}list.innerHTML=state.recruiters.map(r=>`<article class="event-card ${r.active?'':'archived'}"><div class="event-card-main"><div><span class="status">${r.active?'Active':'Inactive'}</span><h3>${esc(r.name)}</h3><p>${esc(r.email)}</p></div><div class="event-actions"><button class="button secondary" data-r-action="toggle" data-id="${r.id}" data-active="${r.active}">${r.active?'Deactivate':'Activate'}</button><button class="button danger" data-r-action="delete" data-id="${r.id}">Delete</button></div></div></article>`).join('')}
async function loadEvents(){const d=await api('/.netlify/functions/events');state.events=d.events||[];renderEvents()}
const eventUrl=s=>`${location.origin}/event/${encodeURIComponent(s)}`;
function renderEvents(){const list=$('eventsList');if(!state.events.length){list.innerHTML='<p>No events yet.</p>';return}list.innerHTML=state.events.map(e=>{const names=(e.recruiterIds||[]).map(id=>state.recruiters.find(r=>r.id===id)?.name).filter(Boolean);return `<article class="event-card ${e.archived?'archived':''}"><div class="event-card-main"><div><span class="status">${e.archived?'Archived':'Active'}</span><h3>${esc(e.name)}</h3><p>${esc([e.date,e.time,e.location].filter(Boolean).join(' • '))}</p><p><strong>Team:</strong> ${esc(names.join(', ')||'None assigned')}</p><a href="${eventUrl(e.slug)}" target="_blank" rel="noopener">${esc(eventUrl(e.slug))}</a></div><div class="event-actions"><button class="button secondary" data-action="copy" data-slug="${e.slug}">Copy Link</button><button class="button secondary" data-action="qr" data-slug="${e.slug}">QR Code</button><button class="button secondary" data-action="registrations" data-slug="${e.slug}">Registrations</button><button class="button secondary" data-action="export" data-slug="${e.slug}">Export CSV</button><button class="button danger" data-action="archive" data-slug="${e.slug}" data-archived="${e.archived}">${e.archived?'Restore':'Archive'}</button></div></div><div class="event-details" id="details-${e.slug}" hidden></div></article>`}).join('')}
async function showRegistrations(slug){const box=$(`details-${slug}`);box.hidden=false;box.innerHTML='<p>Loading…</p>';try{const d=await api(`/.netlify/functions/registrations?slug=${encodeURIComponent(slug)}`),rows=d.registrations||[];box.innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Name</th><th>NMLS</th><th>Phone</th><th>Email</th><th>Invited By</th><th>Bonzo</th><th>Date</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(`${x.firstName} ${x.lastName}`)}</td><td>${esc(x.nmlsId)}</td><td>${esc(x.phone)}</td><td>${esc(x.email)}</td><td>${esc(x.referredBy)}</td><td><span class="sync ${esc(x.bonzoSync?.status||'unknown')}">${esc(x.bonzoSync?.status||'unknown')}</span>${x.bonzoSync?.error?`<small title="${esc(x.bonzoSync.error)}"> View error</small>`:''}</td><td>${esc(new Date(x.createdAt).toLocaleString())}</td></tr>`).join('')}</tbody></table></div>`:'<p>No registrations yet.</p>'}catch(e){box.innerHTML=`<p class="message error">${esc(e.message)}</p>`}}
async function loadBonzo(){try{const d=await api('/.netlify/functions/bonzo');$('bonzoStatus').innerHTML=d.configured?`<p class="message success">Connected: API token is configured.</p><p><strong>Base:</strong> ${esc(d.baseUrl)}<br><strong>Create path:</strong> ${esc(d.createProspectPath)}<br><strong>Assignment:</strong> ${esc(d.assignmentMethod||'assigned_to')}</p>`:'<p class="message error">BONZO_API_TOKEN is not configured.</p>'}catch(e){$('bonzoStatus').textContent=e.message}}
async function downloadProtected(path,filename){const r=await fetch(path,{headers:authHeaders()});if(!r.ok){let m='Download failed.';try{m=(await r.json()).error||m}catch{}throw new Error(m)}const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();state.password=$('passwordInput').value;$('loginMessage').textContent='Logging in…';try{await api('/.netlify/functions/auth',{method:'POST'});sessionStorage.setItem('wclAdminPassword',state.password);$('loginMessage').textContent='';showDashboard();await loadAll()}catch(err){state.password='';sessionStorage.removeItem('wclAdminPassword');$('loginMessage').className='message error';$('loginMessage').textContent=err.message}});
$('logoutButton').onclick=()=>{state.password='';sessionStorage.removeItem('wclAdminPassword');$('passwordInput').value='';showLogin()};
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=true);btn.classList.add('active');$(`tab-${btn.dataset.tab}`).hidden=false});
$('recruiterForm').addEventListener('submit',async e=>{e.preventDefault();const m=$('recruiterMessage');m.textContent='Adding…';try{await api('/.netlify/functions/recruiters',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target).entries()))});e.target.reset();m.className='message success';m.textContent='Team member added.';await loadRecruiters()}catch(err){m.className='message error';m.textContent=err.message}});
$('recruitersList').addEventListener('click',async e=>{const b=e.target.closest('[data-r-action]');if(!b)return;try{if(b.dataset.rAction==='toggle')await api(`/.netlify/functions/recruiters?id=${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({active:b.dataset.active!=='true'})});if(b.dataset.rAction==='delete'&&confirm('Delete this team member?'))await api(`/.netlify/functions/recruiters?id=${b.dataset.id}`,{method:'DELETE'});await loadRecruiters();renderEvents()}catch(err){alert(err.message)}});
$('eventForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),body=Object.fromEntries(fd.entries());body.recruiterIds=fd.getAll('recruiterIds');const m=$('eventFormMessage');m.textContent='Creating…';try{const d=await api('/.netlify/functions/events',{method:'POST',body:JSON.stringify(body)});e.target.reset();renderEventRecruiters();m.className='message success';m.textContent=`Created: ${d.event.name}`;await loadEvents()}catch(err){m.className='message error';m.textContent=err.message}});
$('refreshButton').onclick=loadAll;
$('eventsList').addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,slug}=b.dataset;try{if(action==='copy'){await navigator.clipboard.writeText(eventUrl(slug));b.textContent='Copied!';setTimeout(()=>b.textContent='Copy Link',1200)}if(action==='registrations')await showRegistrations(slug);if(action==='export')await downloadProtected(`/.netlify/functions/export?slug=${encodeURIComponent(slug)}`,`${slug}-registrations.csv`);if(action==='qr')await downloadProtected(`/.netlify/functions/qr?slug=${encodeURIComponent(slug)}`,`${slug}-qr.svg`);if(action==='archive'){await api(`/.netlify/functions/events?slug=${encodeURIComponent(slug)}`,{method:'PATCH',body:JSON.stringify({archived:b.dataset.archived!=='true'})});await loadEvents()}}catch(err){alert(err.message)}});
(async()=>{if(!state.password)return showLogin();try{await api('/.netlify/functions/auth',{method:'POST'});showDashboard();await loadAll()}catch{state.password='';sessionStorage.removeItem('wclAdminPassword');showLogin()}})();
